delete from common.entity_role where entity_id = 21091632 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091632, 'intouch');
delete from common.entity_role where entity_id = 21091632 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091632, 'intouch_correspondence');
delete from common.entity_role where entity_id = 21091632 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091632, 'intouch_case');
delete from common.entity_role where entity_id = 21091632 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091632, 'intouch_case_cdr');
delete from common.entity_role where entity_id = 21091632 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091632, 'intouch_file_shn');
delete from common.entity_role where entity_id = 21091632 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091632, 'intouch_file_shn_cdr');
delete from common.entity_role where entity_id = 21091618 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091618, 'intouch');
delete from common.entity_role where entity_id = 21091618 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091618, 'intouch_correspondence');
delete from common.entity_role where entity_id = 21091618 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091618, 'intouch_case');
delete from common.entity_role where entity_id = 21091618 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091618, 'intouch_case_cdr');
delete from common.entity_role where entity_id = 21091618 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091618, 'intouch_file_shn');
delete from common.entity_role where entity_id = 21091618 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091618, 'intouch_file_shn_cdr');
delete from common.entity_role where entity_id = 21091644 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091644, 'intouch');
delete from common.entity_role where entity_id = 21091644 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091644, 'intouch_correspondence');
delete from common.entity_role where entity_id = 21091644 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091644, 'intouch_case');
delete from common.entity_role where entity_id = 21091644 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091644, 'intouch_case_cdr');
delete from common.entity_role where entity_id = 21091644 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091644, 'intouch_file_shn');
delete from common.entity_role where entity_id = 21091644 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091644, 'intouch_file_shn_cdr');
delete from common.entity_role where entity_id = 21091598 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091598, 'intouch');
delete from common.entity_role where entity_id = 21091598 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091598, 'intouch_correspondence');
delete from common.entity_role where entity_id = 21091598 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091598, 'intouch_case');
delete from common.entity_role where entity_id = 21091598 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091598, 'intouch_case_cdr');
delete from common.entity_role where entity_id = 21091598 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091598, 'intouch_file_shn');
delete from common.entity_role where entity_id = 21091598 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091598, 'intouch_file_shn_cdr');
delete from common.entity_role where entity_id = 21091610 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091610, 'intouch');
delete from common.entity_role where entity_id = 21091610 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091610, 'intouch_correspondence');
delete from common.entity_role where entity_id = 21091610 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091610, 'intouch_case');
delete from common.entity_role where entity_id = 21091610 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091610, 'intouch_case_cdr');
delete from common.entity_role where entity_id = 21091610 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091610, 'intouch_file_shn');
delete from common.entity_role where entity_id = 21091610 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091610, 'intouch_file_shn_cdr');
delete from common.entity_role where entity_id = 21091650 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091650, 'intouch');
delete from common.entity_role where entity_id = 21091650 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091650, 'intouch_correspondence');
delete from common.entity_role where entity_id = 21091650 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091650, 'intouch_case');
delete from common.entity_role where entity_id = 21091650 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091650, 'intouch_case_cdr');
delete from common.entity_role where entity_id = 21091650 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091650, 'intouch_file_shn');
delete from common.entity_role where entity_id = 21091650 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091650, 'intouch_file_shn_cdr');
delete from common.entity_role where entity_id = 21091602 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091602, 'intouch');
delete from common.entity_role where entity_id = 21091602 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091602, 'intouch_correspondence');
delete from common.entity_role where entity_id = 21091602 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091602, 'intouch_case');
delete from common.entity_role where entity_id = 21091602 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091602, 'intouch_case_cdr');
delete from common.entity_role where entity_id = 21091602 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091602, 'intouch_file_shn');
delete from common.entity_role where entity_id = 21091602 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091602, 'intouch_file_shn_cdr');
delete from common.entity_role where entity_id = 21091662 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091662, 'intouch');
delete from common.entity_role where entity_id = 21091662 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091662, 'intouch_correspondence');
delete from common.entity_role where entity_id = 21091662 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091662, 'intouch_case');
delete from common.entity_role where entity_id = 21091662 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091662, 'intouch_case_cdr');
delete from common.entity_role where entity_id = 21091662 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091662, 'intouch_file_shn');
delete from common.entity_role where entity_id = 21091662 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091662, 'intouch_file_shn_cdr');
delete from common.entity_role where entity_id = 21091634 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091634, 'intouch');
delete from common.entity_role where entity_id = 21091634 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091634, 'intouch_correspondence');
delete from common.entity_role where entity_id = 21091634 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091634, 'intouch_case');
delete from common.entity_role where entity_id = 21091634 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091634, 'intouch_case_cdr');
delete from common.entity_role where entity_id = 21091634 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091634, 'intouch_file_shn');
delete from common.entity_role where entity_id = 21091634 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091634, 'intouch_file_shn_cdr');
delete from common.entity_role where entity_id = 21091622 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091622, 'intouch');
delete from common.entity_role where entity_id = 21091622 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091622, 'intouch_correspondence');
delete from common.entity_role where entity_id = 21091622 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091622, 'intouch_case');
delete from common.entity_role where entity_id = 21091622 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091622, 'intouch_case_cdr');
delete from common.entity_role where entity_id = 21091622 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091622, 'intouch_file_shn');
delete from common.entity_role where entity_id = 21091622 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091622, 'intouch_file_shn_cdr');
delete from common.entity_role where entity_id = 21091604 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091604, 'intouch');
delete from common.entity_role where entity_id = 21091604 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091604, 'intouch_correspondence');
delete from common.entity_role where entity_id = 21091604 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091604, 'intouch_case');
delete from common.entity_role where entity_id = 21091604 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091604, 'intouch_case_cdr');
delete from common.entity_role where entity_id = 21091604 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091604, 'intouch_file_shn');
delete from common.entity_role where entity_id = 21091604 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091604, 'intouch_file_shn_cdr');
delete from common.entity_role where entity_id = 21091596 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091596, 'intouch');
delete from common.entity_role where entity_id = 21091596 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091596, 'intouch_correspondence');
delete from common.entity_role where entity_id = 21091596 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091596, 'intouch_case');
delete from common.entity_role where entity_id = 21091596 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091596, 'intouch_case_cdr');
delete from common.entity_role where entity_id = 21091596 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091596, 'intouch_file_shn');
delete from common.entity_role where entity_id = 21091596 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091596, 'intouch_file_shn_cdr');
delete from common.entity_role where entity_id = 21091658 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091658, 'intouch');
delete from common.entity_role where entity_id = 21091658 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091658, 'intouch_correspondence');
delete from common.entity_role where entity_id = 21091658 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091658, 'intouch_case');
delete from common.entity_role where entity_id = 21091658 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091658, 'intouch_case_cdr');
delete from common.entity_role where entity_id = 21091658 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091658, 'intouch_file_shn');
delete from common.entity_role where entity_id = 21091658 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091658, 'intouch_file_shn_cdr');
delete from common.entity_role where entity_id = 21091646 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091646, 'intouch');
delete from common.entity_role where entity_id = 21091646 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091646, 'intouch_correspondence');
delete from common.entity_role where entity_id = 21091646 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091646, 'intouch_case');
delete from common.entity_role where entity_id = 21091646 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091646, 'intouch_case_cdr');
delete from common.entity_role where entity_id = 21091646 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091646, 'intouch_file_shn');
delete from common.entity_role where entity_id = 21091646 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091646, 'intouch_file_shn_cdr');
delete from common.entity_role where entity_id = 21091630 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091630, 'intouch');
delete from common.entity_role where entity_id = 21091630 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091630, 'intouch_correspondence');
delete from common.entity_role where entity_id = 21091630 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091630, 'intouch_case');
delete from common.entity_role where entity_id = 21091630 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091630, 'intouch_case_cdr');
delete from common.entity_role where entity_id = 21091630 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091630, 'intouch_file_shn');
delete from common.entity_role where entity_id = 21091630 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091630, 'intouch_file_shn_cdr');
delete from common.entity_role where entity_id = 21091620 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091620, 'intouch');
delete from common.entity_role where entity_id = 21091620 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091620, 'intouch_correspondence');
delete from common.entity_role where entity_id = 21091620 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091620, 'intouch_case');
delete from common.entity_role where entity_id = 21091620 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091620, 'intouch_case_cdr');
delete from common.entity_role where entity_id = 21091620 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091620, 'intouch_file_shn');
delete from common.entity_role where entity_id = 21091620 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091620, 'intouch_file_shn_cdr');
delete from common.entity_role where entity_id = 21091600 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091600, 'intouch');
delete from common.entity_role where entity_id = 21091600 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091600, 'intouch_correspondence');
delete from common.entity_role where entity_id = 21091600 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091600, 'intouch_case');
delete from common.entity_role where entity_id = 21091600 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091600, 'intouch_case_cdr');
delete from common.entity_role where entity_id = 21091600 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091600, 'intouch_file_shn');
delete from common.entity_role where entity_id = 21091600 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091600, 'intouch_file_shn_cdr');
delete from common.entity_role where entity_id = 21091628 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091628, 'intouch');
delete from common.entity_role where entity_id = 21091628 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091628, 'intouch_correspondence');
delete from common.entity_role where entity_id = 21091628 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091628, 'intouch_case');
delete from common.entity_role where entity_id = 21091628 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091628, 'intouch_case_cdr');
delete from common.entity_role where entity_id = 21091628 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091628, 'intouch_file_shn');
delete from common.entity_role where entity_id = 21091628 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091628, 'intouch_file_shn_cdr');
delete from common.entity_role where entity_id = 21091648 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091648, 'intouch');
delete from common.entity_role where entity_id = 21091648 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091648, 'intouch_correspondence');
delete from common.entity_role where entity_id = 21091648 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091648, 'intouch_case');
delete from common.entity_role where entity_id = 21091648 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091648, 'intouch_case_cdr');
delete from common.entity_role where entity_id = 21091648 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091648, 'intouch_file_shn');
delete from common.entity_role where entity_id = 21091648 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091648, 'intouch_file_shn_cdr');
delete from common.entity_role where entity_id = 21091654 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091654, 'intouch');
delete from common.entity_role where entity_id = 21091654 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091654, 'intouch_correspondence');
delete from common.entity_role where entity_id = 21091654 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091654, 'intouch_case');
delete from common.entity_role where entity_id = 21091654 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091654, 'intouch_case_cdr');
delete from common.entity_role where entity_id = 21091654 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091654, 'intouch_file_shn');
delete from common.entity_role where entity_id = 21091654 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091654, 'intouch_file_shn_cdr');
delete from common.entity_role where entity_id = 21091656 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091656, 'intouch');
delete from common.entity_role where entity_id = 21091656 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091656, 'intouch_correspondence');
delete from common.entity_role where entity_id = 21091656 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091656, 'intouch_case');
delete from common.entity_role where entity_id = 21091656 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091656, 'intouch_case_cdr');
delete from common.entity_role where entity_id = 21091656 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091656, 'intouch_file_shn');
delete from common.entity_role where entity_id = 21091656 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091656, 'intouch_file_shn_cdr');
delete from common.entity_role where entity_id = 21091626 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091626, 'intouch');
delete from common.entity_role where entity_id = 21091626 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091626, 'intouch_correspondence');
delete from common.entity_role where entity_id = 21091626 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091626, 'intouch_case');
delete from common.entity_role where entity_id = 21091626 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091626, 'intouch_case_cdr');
delete from common.entity_role where entity_id = 21091626 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091626, 'intouch_file_shn');
delete from common.entity_role where entity_id = 21091626 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091626, 'intouch_file_shn_cdr');
delete from common.entity_role where entity_id = 21091608 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091608, 'intouch');
delete from common.entity_role where entity_id = 21091608 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091608, 'intouch_correspondence');
delete from common.entity_role where entity_id = 21091608 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091608, 'intouch_case');
delete from common.entity_role where entity_id = 21091608 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091608, 'intouch_case_cdr');
delete from common.entity_role where entity_id = 21091608 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091608, 'intouch_file_shn');
delete from common.entity_role where entity_id = 21091608 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091608, 'intouch_file_shn_cdr');
delete from common.entity_role where entity_id = 21091612 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091612, 'intouch');
delete from common.entity_role where entity_id = 21091612 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091612, 'intouch_correspondence');
delete from common.entity_role where entity_id = 21091612 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091612, 'intouch_case');
delete from common.entity_role where entity_id = 21091612 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091612, 'intouch_case_cdr');
delete from common.entity_role where entity_id = 21091612 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091612, 'intouch_file_shn');
delete from common.entity_role where entity_id = 21091612 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091612, 'intouch_file_shn_cdr');
delete from common.entity_role where entity_id = 21091638 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091638, 'intouch');
delete from common.entity_role where entity_id = 21091638 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091638, 'intouch_correspondence');
delete from common.entity_role where entity_id = 21091638 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091638, 'intouch_case');
delete from common.entity_role where entity_id = 21091638 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091638, 'intouch_case_cdr');
delete from common.entity_role where entity_id = 21091638 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091638, 'intouch_file_shn');
delete from common.entity_role where entity_id = 21091638 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091638, 'intouch_file_shn_cdr');
delete from common.entity_role where entity_id = 21091624 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091624, 'intouch');
delete from common.entity_role where entity_id = 21091624 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091624, 'intouch_correspondence');
delete from common.entity_role where entity_id = 21091624 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091624, 'intouch_case');
delete from common.entity_role where entity_id = 21091624 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091624, 'intouch_case_cdr');
delete from common.entity_role where entity_id = 21091624 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091624, 'intouch_file_shn');
delete from common.entity_role where entity_id = 21091624 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091624, 'intouch_file_shn_cdr');
delete from common.entity_role where entity_id = 21091640 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091640, 'intouch');
delete from common.entity_role where entity_id = 21091640 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091640, 'intouch_correspondence');
delete from common.entity_role where entity_id = 21091640 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091640, 'intouch_case');
delete from common.entity_role where entity_id = 21091640 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091640, 'intouch_case_cdr');
delete from common.entity_role where entity_id = 21091640 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091640, 'intouch_file_shn');
delete from common.entity_role where entity_id = 21091640 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091640, 'intouch_file_shn_cdr');
delete from common.entity_role where entity_id = 21091616 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091616, 'intouch');
delete from common.entity_role where entity_id = 21091616 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091616, 'intouch_correspondence');
delete from common.entity_role where entity_id = 21091616 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091616, 'intouch_case');
delete from common.entity_role where entity_id = 21091616 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091616, 'intouch_case_cdr');
delete from common.entity_role where entity_id = 21091616 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091616, 'intouch_file_shn');
delete from common.entity_role where entity_id = 21091616 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091616, 'intouch_file_shn_cdr');
delete from common.entity_role where entity_id = 21091614 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091614, 'intouch');
delete from common.entity_role where entity_id = 21091614 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091614, 'intouch_correspondence');
delete from common.entity_role where entity_id = 21091614 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091614, 'intouch_case');
delete from common.entity_role where entity_id = 21091614 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091614, 'intouch_case_cdr');
delete from common.entity_role where entity_id = 21091614 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091614, 'intouch_file_shn');
delete from common.entity_role where entity_id = 21091614 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091614, 'intouch_file_shn_cdr');
delete from common.entity_role where entity_id = 21091606 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091606, 'intouch');
delete from common.entity_role where entity_id = 21091606 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091606, 'intouch_correspondence');
delete from common.entity_role where entity_id = 21091606 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091606, 'intouch_case');
delete from common.entity_role where entity_id = 21091606 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091606, 'intouch_case_cdr');
delete from common.entity_role where entity_id = 21091606 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091606, 'intouch_file_shn');
delete from common.entity_role where entity_id = 21091606 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091606, 'intouch_file_shn_cdr');
delete from common.entity_role where entity_id = 21091594 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091594, 'intouch');
delete from common.entity_role where entity_id = 21091594 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091594, 'intouch_correspondence');
delete from common.entity_role where entity_id = 21091594 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091594, 'intouch_case');
delete from common.entity_role where entity_id = 21091594 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091594, 'intouch_case_cdr');
delete from common.entity_role where entity_id = 21091594 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091594, 'intouch_file_shn');
delete from common.entity_role where entity_id = 21091594 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091594, 'intouch_file_shn_cdr');
delete from common.entity_role where entity_id = 21091660 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091660, 'intouch');
delete from common.entity_role where entity_id = 21091660 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091660, 'intouch_correspondence');
delete from common.entity_role where entity_id = 21091660 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091660, 'intouch_case');
delete from common.entity_role where entity_id = 21091660 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091660, 'intouch_case_cdr');
delete from common.entity_role where entity_id = 21091660 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091660, 'intouch_file_shn');
delete from common.entity_role where entity_id = 21091660 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091660, 'intouch_file_shn_cdr');
delete from common.entity_role where entity_id = 21091652 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091652, 'intouch');
delete from common.entity_role where entity_id = 21091652 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091652, 'intouch_correspondence');
delete from common.entity_role where entity_id = 21091652 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091652, 'intouch_case');
delete from common.entity_role where entity_id = 21091652 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091652, 'intouch_case_cdr');
delete from common.entity_role where entity_id = 21091652 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091652, 'intouch_file_shn');
delete from common.entity_role where entity_id = 21091652 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091652, 'intouch_file_shn_cdr');
delete from common.entity_role where entity_id = 21091664 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091664, 'intouch');
delete from common.entity_role where entity_id = 21091664 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091664, 'intouch_correspondence');
delete from common.entity_role where entity_id = 21091664 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091664, 'intouch_case');
delete from common.entity_role where entity_id = 21091664 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091664, 'intouch_case_cdr');
delete from common.entity_role where entity_id = 21091664 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091664, 'intouch_file_shn');
delete from common.entity_role where entity_id = 21091664 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091664, 'intouch_file_shn_cdr');
delete from common.entity_role where entity_id = 21091642 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091642, 'intouch');
delete from common.entity_role where entity_id = 21091642 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091642, 'intouch_correspondence');
delete from common.entity_role where entity_id = 21091642 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091642, 'intouch_case');
delete from common.entity_role where entity_id = 21091642 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091642, 'intouch_case_cdr');
delete from common.entity_role where entity_id = 21091642 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091642, 'intouch_file_shn');
delete from common.entity_role where entity_id = 21091642 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091642, 'intouch_file_shn_cdr');
delete from common.entity_role where entity_id = 21091636 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091636, 'intouch');
delete from common.entity_role where entity_id = 21091636 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091636, 'intouch_correspondence');
delete from common.entity_role where entity_id = 21091636 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091636, 'intouch_case');
delete from common.entity_role where entity_id = 21091636 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091636, 'intouch_case_cdr');
delete from common.entity_role where entity_id = 21091636 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091636, 'intouch_file_shn');
delete from common.entity_role where entity_id = 21091636 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091636, 'intouch_file_shn_cdr');
delete from common.entity_role where entity_id = 21091592 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091592, 'intouch');
delete from common.entity_role where entity_id = 21091592 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091592, 'intouch_correspondence');
delete from common.entity_role where entity_id = 21091592 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091592, 'intouch_case');
delete from common.entity_role where entity_id = 21091592 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091592, 'intouch_case_cdr');
delete from common.entity_role where entity_id = 21091592 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091592, 'intouch_file_shn');
delete from common.entity_role where entity_id = 21091592 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21091592, 'intouch_file_shn_cdr');
delete from common.entity_role where entity_id = 21084940 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21084940, 'intouch');
delete from common.entity_role where entity_id = 21084940 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21084940, 'intouch_correspondence');
delete from common.entity_role where entity_id = 21084940 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21084940, 'intouch_case');
delete from common.entity_role where entity_id = 21084940 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21084940, 'intouch_case_cdr');
delete from common.entity_role where entity_id = 21084940 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21084940, 'intouch_file_shn');
delete from common.entity_role where entity_id = 21084940 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (21084940, 'intouch_file_shn_cdr');
delete from common.entity_role where entity_id = 138790 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (138790, 'intouch');
delete from common.entity_role where entity_id = 138790 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (138790, 'intouch_correspondence');
delete from common.entity_role where entity_id = 138790 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (138790, 'intouch_case');
delete from common.entity_role where entity_id = 138790 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (138790, 'intouch_case_cdr');
delete from common.entity_role where entity_id = 138790 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (138790, 'intouch_file_shn');
delete from common.entity_role where entity_id = 138790 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (138790, 'intouch_file_shn_cdr');
delete from common.entity_role where entity_id = 149030 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (149030, 'intouch');
delete from common.entity_role where entity_id = 149030 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (149030, 'intouch_correspondence');
delete from common.entity_role where entity_id = 149030 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (149030, 'intouch_case');
delete from common.entity_role where entity_id = 149030 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (149030, 'intouch_case_cdr');
delete from common.entity_role where entity_id = 149030 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (149030, 'intouch_file_shn');
delete from common.entity_role where entity_id = 149030 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (149030, 'intouch_file_shn_cdr');
delete from common.entity_role where entity_id = 113259 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (113259, 'intouch');
delete from common.entity_role where entity_id = 113259 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (113259, 'intouch_correspondence');
delete from common.entity_role where entity_id = 113259 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (113259, 'intouch_case');
delete from common.entity_role where entity_id = 113259 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (113259, 'intouch_case_cdr');
delete from common.entity_role where entity_id = 113259 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (113259, 'intouch_file_shn');
delete from common.entity_role where entity_id = 113259 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (113259, 'intouch_file_shn_cdr');
delete from common.entity_role where entity_id = 133098 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (133098, 'intouch');
delete from common.entity_role where entity_id = 133098 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (133098, 'intouch_correspondence');
delete from common.entity_role where entity_id = 133098 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (133098, 'intouch_case');
delete from common.entity_role where entity_id = 133098 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (133098, 'intouch_case_cdr');
delete from common.entity_role where entity_id = 133098 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (133098, 'intouch_file_shn');
delete from common.entity_role where entity_id = 133098 and role_id like 'maa%';
insert into common.entity_role (entity_id, role_id) values (133098, 'intouch_file_shn_cdr');
