insert into p_import.job_class_imp (title, claiming_unit, ccode) values('Academic Counselor','Northern Humboldt Union High School District','NH');
insert into p_import.job_class_imp (title, claiming_unit, ccode) values('Assistant Principal','Northern Humboldt Union High School District','NH');
insert into p_import.job_class_imp (title, claiming_unit, ccode) values('Assistant Superintendent for Business','Northern Humboldt Union High School District','NH');
insert into p_import.job_class_imp (title, claiming_unit, ccode) values('Community Coordinator','Northern Humboldt Union High School District','NH');
insert into p_import.job_class_imp (title, claiming_unit, ccode) values('Counselor','Northern Humboldt Union High School District','NH');
insert into p_import.job_class_imp (title, claiming_unit, ccode) values('Credentialed School Nurse','Northern Humboldt Union High School District','NH');
insert into p_import.job_class_imp (title, claiming_unit, ccode) values('Dean of Students','Northern Humboldt Union High School District','NH');
insert into p_import.job_class_imp (title, claiming_unit, ccode) values('Principal','Northern Humboldt Union High School District','NH');
insert into p_import.job_class_imp (title, claiming_unit, ccode) values('Resource Specialist Teacher','Northern Humboldt Union High School District','NH');
insert into p_import.job_class_imp (title, claiming_unit, ccode) values('School Nurse','Northern Humboldt Union High School District','NH');
insert into p_import.job_class_imp (title, claiming_unit, ccode) values('School Psychologist','Northern Humboldt Union High School District','NH');
insert into p_import.job_class_imp (title, claiming_unit, ccode) values('School Psychologist II','Northern Humboldt Union High School District','NH');
insert into p_import.job_class_imp (title, claiming_unit, ccode) values('School Psychologist Intern','Northern Humboldt Union High School District','NH');
insert into p_import.job_class_imp (title, claiming_unit, ccode) values('Special Ed/SDC Teacher','Northern Humboldt Union High School District','NH');
insert into p_import.job_class_imp (title, claiming_unit, ccode) values('Speech Therapist','Northern Humboldt Union High School District','NH');
insert into p_import.job_class_imp (title, claiming_unit, ccode) values('Superintendent','Northern Humboldt Union High School District','NH');
insert into p_import.job_class_imp (title, claiming_unit, ccode) values('Superintendent''' || 's Secretary','Northern Humboldt Union High School District','NH');
insert into p_import.job_class_imp (title, claiming_unit, ccode) values('Teacher','Northern Humboldt Union High School District','NH');
insert into p_import.job_class_imp (title, claiming_unit, ccode) values('Title One Teacher','Northern Humboldt Union High School District','NH');
insert into p_import.job_class_imp (title, claiming_unit, ccode) values('Transportation Supervisor','Northern Humboldt Union High School District','NH');
