prompt update common.entity set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Stein') and upper(fname) = upper('Adam');
update common.entity_user set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Stein') and upper(fname) = upper('Adam');
prompt update common.entity set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Saether') and upper(fname) = upper('Allison');
update common.entity_user set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Saether') and upper(fname) = upper('Allison');
prompt update common.entity set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Henning') and upper(fname) = upper('Anita');
update common.entity_user set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Henning') and upper(fname) = upper('Anita');
prompt update common.entity set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Lalonde-Berg') and upper(fname) = upper('Anne');
update common.entity_user set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Lalonde-Berg') and upper(fname) = upper('Anne');
prompt update common.entity set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Hautala') and upper(fname) = upper('Ashleigh');
update common.entity_user set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Hautala') and upper(fname) = upper('Ashleigh');
prompt update common.entity set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Arcellana') and upper(fname) = upper('Carole');
update common.entity_user set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Arcellana') and upper(fname) = upper('Carole');
prompt update common.entity set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Perkins') and upper(fname) = upper('Chenoa');
update common.entity_user set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Perkins') and upper(fname) = upper('Chenoa');
prompt update common.entity set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Freed') and upper(fname) = upper('Connie');
update common.entity_user set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Freed') and upper(fname) = upper('Connie');
prompt update common.entity set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Hosmer') and upper(fname) = upper('Cynthia');
update common.entity_user set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Hosmer') and upper(fname) = upper('Cynthia');
prompt update common.entity set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('O'Hare') and upper(fname) = upper('Deborah');
update common.entity_user set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('O'Hare') and upper(fname) = upper('Deborah');
prompt update common.entity set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Struven') and upper(fname) = upper('Denise');
update common.entity_user set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Struven') and upper(fname) = upper('Denise');
prompt update common.entity set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Wilcox') and upper(fname) = upper('Diana');
update common.entity_user set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Wilcox') and upper(fname) = upper('Diana');
prompt update common.entity set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Parker') and upper(fname) = upper('Diane');
update common.entity_user set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Parker') and upper(fname) = upper('Diane');
prompt update common.entity set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Poninski') and upper(fname) = upper('Donna');
update common.entity_user set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Poninski') and upper(fname) = upper('Donna');
prompt update common.entity set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Jordan') and upper(fname) = upper('Emily');
update common.entity_user set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Jordan') and upper(fname) = upper('Emily');
prompt update common.entity set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Weber') and upper(fname) = upper('Esther');
update common.entity_user set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Weber') and upper(fname) = upper('Esther');
prompt update common.entity set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Miller') and upper(fname) = upper('Gail');
update common.entity_user set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Miller') and upper(fname) = upper('Gail');
prompt update common.entity set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Perez') and upper(fname) = upper('Gerard');
update common.entity_user set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Perez') and upper(fname) = upper('Gerard');
prompt update common.entity set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Jackson') and upper(fname) = upper('Gladys');
update common.entity_user set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Jackson') and upper(fname) = upper('Gladys');
prompt update common.entity set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Delgadillo') and upper(fname) = upper('Irma');
update common.entity_user set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Delgadillo') and upper(fname) = upper('Irma');
prompt update common.entity set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Todd') and upper(fname) = upper('Jan');
update common.entity_user set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Todd') and upper(fname) = upper('Jan');
prompt update common.entity set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('O'Malley') and upper(fname) = upper('Janice');
update common.entity_user set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('O'Malley') and upper(fname) = upper('Janice');
prompt update common.entity set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Grottkau') and upper(fname) = upper('Janie');
update common.entity_user set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Grottkau') and upper(fname) = upper('Janie');
prompt update common.entity set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Bockman') and upper(fname) = upper('Jill');
update common.entity_user set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Bockman') and upper(fname) = upper('Jill');
prompt update common.entity set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Bailey') and upper(fname) = upper('Joan');
update common.entity_user set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Bailey') and upper(fname) = upper('Joan');
prompt update common.entity set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Scudero') and upper(fname) = upper('Kate');
update common.entity_user set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Scudero') and upper(fname) = upper('Kate');
prompt update common.entity set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Dillon') and upper(fname) = upper('Kourtney');
update common.entity_user set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Dillon') and upper(fname) = upper('Kourtney');
prompt update common.entity set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Gordon') and upper(fname) = upper('Larry');
update common.entity_user set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Gordon') and upper(fname) = upper('Larry');
prompt update common.entity set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Chait') and upper(fname) = upper('Leslie');
update common.entity_user set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Chait') and upper(fname) = upper('Leslie');
prompt update common.entity set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Barbour-Kambe') and upper(fname) = upper('Linda');
update common.entity_user set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Barbour-Kambe') and upper(fname) = upper('Linda');
prompt update common.entity set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Ebeling') and upper(fname) = upper('Lisa');
update common.entity_user set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Ebeling') and upper(fname) = upper('Lisa');
prompt update common.entity set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Schamberger') and upper(fname) = upper('Loretta');
update common.entity_user set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Schamberger') and upper(fname) = upper('Loretta');
prompt update common.entity set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Black') and upper(fname) = upper('Lynda');
update common.entity_user set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Black') and upper(fname) = upper('Lynda');
prompt update common.entity set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Hildebrandt') and upper(fname) = upper('Margaret');
update common.entity_user set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Hildebrandt') and upper(fname) = upper('Margaret');
prompt update common.entity set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Aguilar') and upper(fname) = upper('Maria');
update common.entity_user set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Aguilar') and upper(fname) = upper('Maria');
prompt update common.entity set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Bergfelt') and upper(fname) = upper('Marilane');
update common.entity_user set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Bergfelt') and upper(fname) = upper('Marilane');
prompt update common.entity set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Cossette') and upper(fname) = upper('Marilyn');
update common.entity_user set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Cossette') and upper(fname) = upper('Marilyn');
prompt update common.entity set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Lopez') and upper(fname) = upper('Martha');
update common.entity_user set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Lopez') and upper(fname) = upper('Martha');
prompt update common.entity set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Lopez') and upper(fname) = upper('Martha');
update common.entity_user set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Lopez') and upper(fname) = upper('Martha');
prompt update common.entity set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Chavez') and upper(fname) = upper('Maureen');
update common.entity_user set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Chavez') and upper(fname) = upper('Maureen');
prompt update common.entity set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Redmond') and upper(fname) = upper('Nancy');
update common.entity_user set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Redmond') and upper(fname) = upper('Nancy');
prompt update common.entity set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Delegeane') and upper(fname) = upper('Nyda');
update common.entity_user set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Delegeane') and upper(fname) = upper('Nyda');
prompt update common.entity set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Green') and upper(fname) = upper('Paula');
update common.entity_user set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Green') and upper(fname) = upper('Paula');
prompt update common.entity set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Klyce') and upper(fname) = upper('Pilar');
update common.entity_user set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Klyce') and upper(fname) = upper('Pilar');
prompt update common.entity set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Abernathy-Grottkau') and upper(fname) = upper('Rebekah');
update common.entity_user set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Abernathy-Grottkau') and upper(fname) = upper('Rebekah');
prompt update common.entity set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Anderson') and upper(fname) = upper('Robert');
update common.entity_user set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Anderson') and upper(fname) = upper('Robert');
prompt update common.entity set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Bruce') and upper(fname) = upper('Sandra');
update common.entity_user set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Bruce') and upper(fname) = upper('Sandra');
prompt update common.entity set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Fox') and upper(fname) = upper('Sandra');
update common.entity_user set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Fox') and upper(fname) = upper('Sandra');
prompt update common.entity set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Skaggs') and upper(fname) = upper('Sarah');
update common.entity_user set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Skaggs') and upper(fname) = upper('Sarah');
prompt update common.entity set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Hollman') and upper(fname) = upper('Sherri');
update common.entity_user set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Hollman') and upper(fname) = upper('Sherri');
prompt update common.entity set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Ziegler-Springe') and upper(fname) = upper('Stacey');
update common.entity_user set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Ziegler-Springe') and upper(fname) = upper('Stacey');
prompt update common.entity set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Korsmo') and upper(fname) = upper('Suqui');
update common.entity_user set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Korsmo') and upper(fname) = upper('Suqui');
prompt update common.entity set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Dawson') and upper(fname) = upper('Susan');
update common.entity_user set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Dawson') and upper(fname) = upper('Susan');
prompt update common.entity set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Schroeder') and upper(fname) = upper('Susan');
update common.entity_user set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Schroeder') and upper(fname) = upper('Susan');
prompt update common.entity set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Wood Deguilio') and upper(fname) = upper('Susan');
update common.entity_user set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Wood Deguilio') and upper(fname) = upper('Susan');
prompt update common.entity set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Sanchez') and upper(fname) = upper('Suzanne');
update common.entity_user set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Sanchez') and upper(fname) = upper('Suzanne');
prompt update common.entity set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Shuster') and upper(fname) = upper('Terry');
update common.entity_user set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Shuster') and upper(fname) = upper('Terry');
prompt update common.entity set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Peck') and upper(fname) = upper('Vickie');
update common.entity_user set ccode = 'NV' where ccode = 'GN' and upper(lname) = upper('Peck') and upper(fname) = upper('Vickie');
